INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-3dtrackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-borders', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-borders-broadcast', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-borders-html', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-extended-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-fly-over-alerts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-fonts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-help', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-modes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-personalities', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-profiles', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-routes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-scripts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-terminal-maps', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-trackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-triggers', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-configuration-world-guide', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-content', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-content-airports', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-content-logos', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-content-placenames', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'custom-content-splash-screen', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'flight-info-max-parameters', N'15')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'flight-info-parameters', N'eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled,eDistanceToDestination,eTimeToDestination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'flight-info-parameters-display', N'Local Time At Present Position,Local Time At Dest City Name,Estimated Time Of Arrival, Time To Dest City Name,Time Since Departure, Distance To Dest City Name,Latitude,Longitude,Heading, Head wind Tail wind,Wind Direction,Wind Speed,Altitude,Ground Speed,Outside Air Temperature,True Airspeed,Mach,Distance Traveled,Distance To Destination,Time to Destination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'layers', N'distance to poi,trackline,compass,hud,night,borders,north indicator,fodors,pn cities,pn capitals,pn land features,pn water features,pn_airports,terrain,pn airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'layers-display', N'Distance To Poi,Trackline,Compass,HUD,Night,Borders,North Indicator,Fodors,Cities,Capitals,Land Features,Water Features,Airports,Terrain,Airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'makkah-calculation-types', N'mwl,jafari,karachi,isna,makkah,egypt,tehran')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'makkah-calculation-types-display', N'MWL (Muslim World League),Jafari (Shia Ithana Ashari, Leva Research Institute),Karachi (University of Islamic Science),ISNA (Islamic Society of North America),Makkah (Umm Al-Quara University),
Egypt (Egyptian General Authority of Survey),Tehran (Institute of Geophysics, University of Tehran)')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'name', N'baseline feature set')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'script', N'e3DPreFlight,e3DMidFlight,e3DZspace,e3DRli,e3DPanorama,e3DImage,e3DOverhead,e3DVideo,e3DFlightData,e3DRotatingPOI,e3DTotalRoute,e3DTimezone,e3DWorldClocks,e3DRliMecca,e3DHighestRes,e3DMakkah,e3DMiqat,eTickerImage,eTickerFd')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'script-display', N'Flight Preview,Midflight,Global Zoom,Compass,Window Seat,Image,Overhead,Video,Flight Info,Points of Interest,Total Route,Timezone Globe,World Clocks,Makkah Compass,High Resolution,Makkah,Miqat,Ticker Image,Ticker Info')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'ticker-max-speed', N'7')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'ticker-min-speed', N'1')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'ticker-parameters', N'eLocalTimeAtDestination,eLocalTimeAtDeparture,eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestination,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestination,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'ticker-parameters-display', N'Local Time At Destination,Local Time At Departure,Local Time At Departure ,Local Time At Destination,Estimated Time Of Arrival,Time To Destination,Time To Destination,Time Since Departure,Distance To Destination,Distance To Destination,Latitude,Longitude,Heading,Headwind Tailwind,Wind Direction,Wind Speed,Altitude,GroundSpeed,Outside Air Temperature,TrueAirspeed,Mach,DistancTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'views', N'autoplay,flight preview,total route,landscape,overhead,compass,world clocks,time zone, panorama,flight info,command center,makkah,rotating poi')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'views-display', N'Autoplay,Flight Preview,Total Route,Mid Flight,Overhead, Compass,World Clocks,Timezone Globe,Window Seat,Flight Information, Command Center,Makkah,Points of Interest')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'views-max-presets', N'3')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'world-clocks-max-cities', N'12')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'collins-admin-items', N'flight-data,system-config,briefings,timezone-database,world-guide,insets,download-test-configuration,populations,placenames,airports,world-guide-cities');
GO

--
-- global configuration feature set flags
--
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-3dtrackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-borders', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-borders-broadcast', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-borders-html', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-extended-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-fly-over-alerts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-fonts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-help', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-modes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-personalities', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-profiles', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-routes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-scripts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-terminal-maps', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-trackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-triggers', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-world-guide', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-airports', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-logos', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-placenames', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-splash-screen', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'flight-info-max-parameters', N'15')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'flight-info-parameters', N'eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled,eDistanceToDestination,eTimeToDestination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'flight-info-parameters-display', N'Local Time At Present Position,Local Time At Dest City Name,Estimated Time Of Arrival, Time To Dest City Name,Time Since Departure, Distance To Dest City Name,Latitude,Longitude,Heading, Head wind Tail wind,Wind Direction,Wind Speed,Altitude,Ground Speed,Outside Air Temperature,True Airspeed,Mach,Distance Traveled,Distance To Destination,Time to Destination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'layers', N'distance to poi,trackline,compass,hud,night,borders,north indicator,fodors,pn cities,pn capitals,pn land features,pn water features,pn_airports,terrain,pn airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'layers-display', N'Distance To Poi,Trackline,Compass,HUD,Night,Borders,North Indicator,Fodors,Cities,Capitals,Land Features,Water Features,Airports,Terrain,Airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'makkah-calculation-types', N'mwl,jafari,karachi,isna,makkah,egypt,tehran')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'makkah-calculation-types-display', N'MWL (Muslim World League),Jafari (Shia Ithana Ashari, Leva Research Institute),Karachi (University of Islamic Science),ISNA (Islamic Society of North America),Makkah (Umm Al-Quara University),
Egypt (Egyptian General Authority of Survey),Tehran (Institute of Geophysics, University of Tehran)')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'name', N'global configuration feature set')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'script', N'e3DPreFlight,e3DMidFlight,e3DZspace,e3DRli,e3DPanorama,e3DImage,e3DOverhead,e3DVideo,e3DFlightData,e3DRotatingPOI,e3DTotalRoute,e3DTimezone,e3DWorldClocks,e3DRliMecca,e3DHighestRes,e3DMakkah,e3DMiqat,eTickerImage,eTickerFd')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'script-display', N'Flight Preview,Midflight,Global Zoom,Compass,Window Seat,Image,Overhead,Video,Flight Info,Points of Interest,Total Route,Timezone Globe,World Clocks,Makkah Compass,High Resolution,Makkah,Miqat,Ticker Image,Ticker Info')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-max-speed', N'7')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-min-speed', N'1')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-parameters', N'eLocalTimeAtDestination,eLocalTimeAtDeparture,eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestination,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestination,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-parameters-display', N'Local Time At Destination,Local Time At Departure,Local Time At Departure ,Local Time At Destination,Estimated Time Of Arrival,Time To Destination,Time To Destination,Time Since Departure,Distance To Destination,Distance To Destination,Latitude,Longitude,Heading,Headwind Tailwind,Wind Direction,Wind Speed,Altitude,GroundSpeed,Outside Air Temperature,TrueAirspeed,Mach,DistancTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'views', N'autoplay,flight preview,total route,landscape,overhead,compass,world clocks,time zone, panorama,flight info,command center,makkah,rotating poi')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'views-display', N'Autoplay,Flight Preview,Total Route,Mid Flight,Overhead, Compass,World Clocks,Timezone Globe,Window Seat,Flight Information, Command Center,Makkah,Points of Interest')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'views-max-presets', N'3')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'world-clocks-max-cities', N'12')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'collins-admin-items', N'populations,placenames,airports,world-guide-cities');
GO