SET IDENTITY_INSERT [dbo].[tblInfoSpelling] ON 

INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (1, 0, 1, N'Ground Speed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (2, 1, 1, N'Distance to Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (3, 2, 1, N'True Airspeed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (4, 3, 1, N'Altitude')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (5, 4, 1, N'Latitude')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (6, 5, 1, N'Longitude')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (7, 6, 1, N'Time to Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (8, 7, 1, N'Wind Speed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (9, 8, 1, N'Wind Direction')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (10, 9, 1, N'Heading')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (11, 10, 1, N'Outside Air Temperature')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (12, 11, 1, N'Greenwich Mean Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (13, 12, 1, N'Direction to Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (14, 13, 1, N'Mach')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (15, 14, 1, N'Time Since Departure')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (16, 15, 1, N'Distance from Departure')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (17, 16, 1, N'Distance Traveled')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (18, 17, 1, N'Date')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (19, 18, 1, N'Sunday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (20, 19, 1, N'Monday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (21, 20, 1, N'Tuesday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (22, 21, 1, N'Wednesday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (23, 22, 1, N'Thursday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (24, 23, 1, N'Friday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (25, 24, 1, N'Saturday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (26, 25, 1, N'Pacific Standard Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (27, 26, 1, N'Pacific Daylight Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (28, 27, 1, N'Mountain Standard Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (29, 28, 1, N'Mountain Daylight Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (30, 29, 1, N'Central Standard Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (31, 30, 1, N'Central Daylight Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (32, 31, 1, N'Eastern Standard Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (33, 32, 1, N'Eastern Daylight Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (34, 33, 1, N'Day')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (35, 34, 1, N'Local Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (36, 35, 1, N'Local Time at Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (37, 36, 1, N'Estimated Arrival Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (38, 37, 1, N'Local Time at Origin')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (39, 38, 1, N'')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (40, 39, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (41, 40, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (42, 41, 1, N'ETA at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (43, 42, 1, N'Head Wind')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (44, 43, 1, N'Tail Wind')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (45, 44, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (46, 45, 1, N'TSD from')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (47, 46, 1, N'Distance from')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (48, 47, 1, N'Time to')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (49, 48, 1, N'Distance to')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (50, 49, 1, N'Departure')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (51, 50, 1, N'Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (52, 51, 1, N'')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (53, 52, 1, N'mph')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (54, 53, 1, N'km/h')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (55, 54, 1, N'knots')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (56, 55, 1, N'feet')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (57, 56, 1, N'mi')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (58, 57, 1, N'nmi')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (59, 58, 1, N'km')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (60, 59, 1, N'°C')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (61, 60, 1, N'°F')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (62, 61, 1, N'm')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (63, 62, 1, N'm/d/y')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (64, 63, 1, N'N')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (65, 64, 1, N'E')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (66, 65, 1, N'S')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (67, 66, 1, N'W')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (68, 67, 1, N'deg')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (69, 68, 1, N'am')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (70, 69, 1, N'pm')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (71, 70, 1, N'')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (72, 71, 1, N':')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (73, 72, 1, N'd/m/y')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (74, 73, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (75, 74, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (76, 75, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (77, 76, 1, N'Local Time at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (78, 77, 1, N'Temperature')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (79, 78, 1, N'Local Weather at')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (80, 79, 1, N'Weather Conditions at Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (81, 80, 1, N'Current Time:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (82, 81, 1, N'Total Distance')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (83, 82, 1, N'Total Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (84, 83, 1, N'Flight Status')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (85, 84, 1, N'Flight Information')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (86, 85, 1, N'Date at GMT')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (87, 86, 1, N'Compass')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (88, 87, 1, N'')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (89, 88, 1, N'')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (90, 89, 1, N'Head Wind')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (91, 90, 1, N'')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (92, 91, 1, N'Vertical Speed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (93, 92, 1, N'ft/min')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (94, 93, 1, N'm/min')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (95, 94, 1, N'Pitch')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (96, 95, 1, N'Roll')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (97, 96, 1, N'°')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (98, 1000, 1, N'Overview')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (99, 1001, 1, N'Slide Show')
GO
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (100, 1002, 1, N'Features')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (101, 1003, 1, N'Sights')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (102, 1004, 1, N'Stats')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (103, 1005, 1, N'Loading, Please Wait')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (104, 1006, 1, N'Click anywhere on the map to zoom in')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (105, 1007, 1, N'Distance from Aircraft')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (106, 1008, 1, N'Population')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (107, 1009, 1, N'Elevation')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (108, 1010, 1, N'Flight Specific Views')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (109, 1011, 1, N'Interactive Views')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (110, 1012, 1, N'Total Route')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (111, 1013, 1, N'Day / Night')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (112, 1014, 1, N'Autozoom')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (113, 1015, 1, N'High Resolution')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (114, 1016, 1, N'World Explorer')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (115, 1017, 1, N'Location Indicator')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (116, 1018, 1, N'Departure')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (117, 1019, 1, N'Destination')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (118, 1020, 1, N'Closest')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (119, 1021, 1, N'Arrival Gate')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (120, 1022, 1, N'Gate Information')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (121, 1023, 1, N'Terminal Map')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (122, 1024, 1, N'Flight:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (123, 1025, 1, N'Arrival Gate:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (124, 1026, 1, N'Baggage Claim:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (125, 1027, 1, N'Arrival Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (126, 1028, 1, N'DEPARTING TO')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (127, 1029, 1, N'STATUS')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (128, 1030, 1, N'FLIGHT')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (129, 1031, 1, N'GATE')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (130, 1032, 1, N'TIME')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (131, 1033, 1, N'ARRIVAL GATE INFORMATION')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (132, 1034, 1, N'Boarding')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (133, 1035, 1, N'Cancelled')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (134, 1036, 1, N'Delayed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (135, 1037, 1, N'On Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (136, 1038, 1, N'Rebooked')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (137, 1039, 1, N'See Agent')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (138, 1040, 1, N'Last Update (GMT)')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (139, 1041, 1, N'Arrival Gate is Currently Not Available')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (140, 1042, 1, N'Gate Information is Currently Not Available')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (141, 1043, 1, N'Terminal Map is Currently Not Available')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (142, 1044, 1, N'Gate Change')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (143, 1045, 1, N'Time Zone')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (144, 1046, 1, N'Time to Miqat')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (145, 1047, 1, N'Ihram Zone')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (146, 1048, 1, N'Terminal View')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (147, 1049, 1, N'Terminal View 1')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (148, 1050, 1, N'Terminal View 2')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (149, 1051, 1, N'Terminal View 3')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (150, 1052, 1, N'Destination Information is Currently Not Available')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (151, 1053, 1, N'Application Currently Unavailable')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (152, 1054, 1, N'Flight Data Unavailable')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (153, 1055, 1, N'Please Wait')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (154, 1056, 1, N'MAP VIEWS')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (155, 1057, 1, N'3D Maps')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (156, 1058, 1, N'Time Zone')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (157, 1059, 1, N'Regional Zoom')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (158, 1060, 1, N'3D Global Zoom')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (159, 1061, 1, N'Compass')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (160, 1062, 1, N'Current Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (161, 1063, 1, N'Your Flight')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (162, 1064, 1, N'Autoplay')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (163, 1065, 1, N'Cycle Maps')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (164, 1066, 1, N'Language')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (165, 1067, 1, N'Units of Measurement')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (166, 1068, 1, N'Time Format')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (167, 1069, 1, N'Map Package')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (168, 1070, 1, N'Monitor')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (169, 1071, 1, N'Display Mode')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (170, 1072, 1, N'Map Settings')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (171, 1073, 1, N'Configurable Displays')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (172, 1074, 1, N'Destination Airport Code')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (173, 1075, 1, N'Metric')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (174, 1076, 1, N'Imperial')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (175, 1077, 1, N'Cycle')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (176, 1078, 1, N'24 Hour')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (177, 1079, 1, N'12 Hour')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (178, 1080, 1, N'Logo')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (179, 1081, 1, N'Pre Flight')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (180, 1082, 1, N'Override')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (181, 1083, 1, N'Cancel')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (182, 1084, 1, N'Restore Defaults')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (183, 1085, 1, N'Submit')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (184, 1086, 1, N'Today')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (185, 1087, 1, N'Tomorrow')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (186, 1088, 1, N'Yesterday')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (187, 1089, 1, N'HR')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (188, 1090, 1, N'MIN')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (189, 1091, 1, N'January')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (190, 1092, 1, N'February')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (191, 1093, 1, N'March')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (192, 1094, 1, N'April')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (193, 1095, 1, N'May')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (194, 1096, 1, N'June')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (195, 1097, 1, N'July')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (196, 1098, 1, N'August')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (197, 1099, 1, N'September')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (198, 1100, 1, N'October')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (199, 1101, 1, N'November')
GO
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (200, 1102, 1, N'December')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (201, 1103, 1, N'Distance')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (202, 1104, 1, N'to')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (203, 1105, 1, N'Time')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (204, 1200, 1, N'Settings')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (205, 1201, 1, N'Language - ')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (206, 1202, 1, N'Select the language to be used within the application.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (207, 1203, 1, N'Select the time format to be used within the application.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (208, 1204, 1, N'Nautical')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (209, 1205, 1, N'Select the units of measurement to be used within the application.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (210, 1206, 1, N'Compass Arrow One')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (211, 1207, 1, N'Compass Arrow Two')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (212, 1208, 1, N'Track the distance of two cities from your current in-flight position.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (213, 1209, 1, N'World Clocks')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (214, 1210, 1, N'Add, remove and rearrange the World Clocks that are displayed in the application.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (215, 1211, 1, N'Ticker')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (216, 1212, 1, N'Show Ticker')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (217, 1213, 1, N'Hide Ticker')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (218, 1214, 1, N'Turn on/off the flight information ticker at the bottom of the screen.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (219, 1215, 1, N'Done')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (220, 1216, 1, N'Flight Preview')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (221, 1217, 1, N'Panorama')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (222, 1218, 1, N'Mid Flight')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (223, 1219, 1, N'camera')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (224, 1220, 1, N'City Information')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (225, 1221, 1, N'Makkah')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (226, 1222, 1, N'Closest City')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (227, 1223, 1, N'Destination City')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (228, 1224, 1, N'Departure City')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (229, 1225, 1, N'All')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (230, 1226, 1, N'Distance to City')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (231, 1227, 1, N'Trackline')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (232, 1228, 1, N'Compass')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (233, 1229, 1, N'HUD')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (234, 1230, 1, N'Night')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (235, 1231, 1, N'Miqat')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (236, 1232, 1, N'Borders')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (237, 1233, 1, N'Auto Play')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (238, 1234, 1, N'Flight Preview')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (239, 1235, 1, N'Total Route')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (240, 1236, 1, N'Mid Flight')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (241, 1237, 1, N'Overhead')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (242, 1238, 1, N'Compass')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (243, 1239, 1, N'World Clocks')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (244, 1240, 1, N'Time Zones')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (245, 1241, 1, N'Window Seat')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (246, 1242, 1, N'Test Scene')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (247, 1243, 1, N'Global Zoom')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (248, 1244, 1, N'Diagnostics')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (249, 1245, 1, N'Flight Data')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (250, 1246, 1, N'Time Format')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (251, 1247, 1, N'12 Hr')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (252, 1248, 1, N'24 Hr')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (253, 1249, 1, N'Units')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (254, 1250, 1, N'Metric')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (255, 1251, 1, N'Imperial')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (256, 1252, 1, N'Nautical')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (257, 1253, 1, N'Menu Position')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (258, 1254, 1, N'Left')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (259, 1255, 1, N'Right')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (260, 1256, 1, N'Ticker Visibility')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (261, 1257, 1, N'Hide')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (262, 1258, 1, N'Show')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (263, 1259, 1, N'Speed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (264, 1260, 1, N'Slow')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (265, 1261, 1, N'Fast')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (266, 1262, 1, N'Map Key')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (267, 1263, 1, N'Views')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (268, 1264, 1, N'Layers')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (269, 1265, 1, N'Settings')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (270, 1266, 1, N'Country Capitals')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (271, 1267, 1, N'Cities')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (272, 1268, 1, N'Water Features')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (273, 1269, 1, N'State Capitals')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (274, 1270, 1, N'Geographic Features')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (275, 1271, 1, N'Airports')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (276, 1272, 1, N'MAP KEY')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (277, 1273, 1, N'Map icons with additional content')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (278, 1274, 1, N'Map icons without additional content')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (279, 1275, 1, N'North Indicator')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (280, 1276, 1, N'Travel Guide')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (281, 1277, 1, N'Cities')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (282, 1278, 1, N'Capitals')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (283, 1279, 1, N'Geographic Features')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (284, 1280, 1, N'Water Features')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (285, 1281, 1, N'Airports')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (286, 1282, 1, N'Awaiting Position Report')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (287, 1283, 1, N'Cannot go back from Autoplay')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (288, 1284, 1, N'Search for Locations')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (289, 1285, 1, N'Pitch and Roll')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (290, 1286, 1, N'Command Center')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (291, 1287, 1, N'Airspeed')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (292, 1288, 1, N'Pitch / Roll')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (293, 1289, 1, N'Terrain')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (294, 1300, 1, N'Makkah Pointer')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (295, 1301, 1, N'Change Location')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (296, 1302, 1, N'Fajr')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (297, 1303, 1, N'Sunrise')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (298, 1304, 1, N'Dhuhr')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (299, 1305, 1, N'Asr')
GO
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (300, 1306, 1, N'Maghrib')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (301, 1307, 1, N'Isha')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (302, 1308, 1, N'Time Until Prayer')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (303, 1309, 1, N'Current Location')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (304, 1310, 1, N'hh')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (305, 1311, 1, N'mm')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (306, 1312, 1, N'Prayer Location:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (307, 1313, 1, N'Auto Zoom')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (308, 1314, 1, N'City Lights')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (309, 1315, 1, N'hour')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (310, 1316, 1, N'hours')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (311, 1317, 1, N'minute')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (312, 1318, 1, N'minutes')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (313, 1319, 1, N'Time to (PRAYER): ')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (314, 1320, 1, N'Prayer times in ')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (315, 1321, 1, N'Prayer times at ')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (316, 1322, 1, N'Prayer Location')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (317, 1330, 1, N'Street Maps server connection lost.')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (318, 1349, 1, N'Next Up')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (319, 1352, 1, N'Time:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (320, 1353, 1, N'Distance:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (321, 1334, 1, N'Points of Interest')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (322, 1340, 1, N'(TIME) To Arrival')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (323, 1341, 1, N'Media Share')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (324, 1342, 1, N'Ticker Settings')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (325, 1343, 1, N'City Guide')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (326, 1344, 1, N'Help')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (327, 1345, 1, N'Map Themes')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (328, 1332, 1, N'Edit Cities')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (329, 1333, 1, N'Add City')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (330, 1347, 1, N'Ticker Position')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (331, 1348, 1, N'Standard')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (332, 1354, 1, N'Clock')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (333, 1356, 1, N'Sort by')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (334, 1357, 1, N'Added')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (335, 1358, 1, N'Location')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (336, 1350, 1, N'No Points of Interest to display')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (337, 1351, 1, N'Side of the aircraft:')
INSERT [dbo].[tblInfoSpelling] ([InfoSpellingId], [InfoId], [LanguageId], [Spelling]) VALUES (338, 1346, 1, N'Units of Measurement')
SET IDENTITY_INSERT [dbo].[tblInfoSpelling] OFF
GO

INSERT [dbo].[tblTaskDataType] ([ID], [Name], [Description]) VALUES (N'e33b169a-198a-4917-b53e-7cf7864b090e', N'Configuration ID', NULL)
INSERT [dbo].[tblTaskDataType] ([ID], [Name], [Description]) VALUES (N'81bf8ff8-32eb-4c8e-813d-f98be79c5bf5', N'Configuration Definition ID', NULL)
GO

INSERT [dbo].[tblTaskStatus] ([ID], [Name], [Description]) VALUES (1, N'Not Started', N'export-product-database')
INSERT [dbo].[tblTaskStatus] ([ID], [Name], [Description]) VALUES (2, N'In Progress', N'export-product-database')
INSERT [dbo].[tblTaskStatus] ([ID], [Name], [Description]) VALUES (3, N'Failed', NULL)
INSERT [dbo].[tblTaskStatus] ([ID], [Name], [Description]) VALUES (4, N'Succeeded', NULL)
GO
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'ed0d1e4e-cb7f-4356-b366-33fe4fb50129', N'Export Product Database - Thales', NULL, NULL)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'd693ad3a-4575-464d-ac5f-353a0db02146', N'Export Product Database - PAC3D', NULL, NULL)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'b53297b7-8c0c-4452-9d58-393973558ffd', N'Export Development Config', N'Export development internal config', NULL)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'0d67043d-e490-448e-aeb6-399cbe2f51b6', N'Export Product Database - AS4XXX', NULL, NULL)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'00b9d873-5a19-43d7-b085-a7444a5babf2', N'Export Product Database - CESHTSE', NULL, NULL)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'dc1610ba-e8b9-43ba-91f4-f56685820b9e', N'Export Product Database', N'Not Used!', 2352)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0333', N'Import Initial Config', N'Import Initial Config Desc', 333)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0444', N'Import Initial Config - custom.xml', N'Import Initial Config - custom.xml', 444)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0555', N'Import Initial Config - asxiprofile.xml', N'Import Initial Config - asxiprofile.xml', 555)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0666', N'Import CityPopulation', N'Import CityPopulation', 666)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0777', N'Import NewAirportFromNavDB', N'Import NewAirportFromNavDB', 777)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0888', N'Import WGCities', N'Import WGCities', 888)
INSERT [dbo].[tblTaskType] ([ID], [Name], [Description], [AzureDefinitionID]) VALUES (N'c56a4180-65aa-42ec-a945-5fd21dec0999', N'MergCofiguration', N'MergCofiguration', 999)
GO

INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (1, N'Global', 1, 1)
INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (2, N'ASXi4/5', 1, 1)
INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (3, N'AS4XXX', 1, 1)
INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (4, N'AS500', 1, 1)
INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (5, N'CES', 1, 1)
INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (6, N'Thales2D', 1, 1)
INSERT [dbo].[tblConfigurationTypes] ([ConfigurationTypeID], [Name], [UsesTimezone], [UsesPlacenames]) VALUES (7, N'ASXi 3', 1, 1)
GO

INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (1, N'AS4XXX')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (2, N'AS500')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (3, N'CES')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (4, N'Thales2D')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (5, N'Pac3D')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (6, N'ASXi 3/4 Hybrid')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (7, N'ASXi 4/5')
INSERT [dbo].[tblOutputTypes] ([OutputTypeID], [OutputTypeName]) VALUES (8, N'N/A')
GO

INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblTimeZoneGlobePlaceNames')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontFiles')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblTzPois')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWebMain')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblMetroMapGeoRefs')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontFileSelection')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWorldClockCities')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWorldMapCities')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWorldMapPlaceNames')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblConfigVersion')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWorldTimeZonePlaceNames')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblAirportInfo')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblAppearance')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblArea')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblAsxiWorldGuideText')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblCityPopulation')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblInfoSpelling')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblScreenSize')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblCountry')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblCountrySpelling')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblSpelling')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblCoverageSegment')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblSpellingPoiPanel')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblElevation')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblAsxiProfile')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblTimeZoneStrip')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontCategory')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblNews')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontDefaultCategory')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontFamily')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFont')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontMarker')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFontTextEffect')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblFlyOverAlert')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWGContent')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblGlobal')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWGImage')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblHandSet')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWGType')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblConfigurationComponents')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblMaps')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblRegionSpelling')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblMakkah')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblMenu')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblMapInsets')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblMiqat')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblHtml5')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblGeoRef')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblModeDefs')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblPersonalityList')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblTrigger')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblASXiInset')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblResolution')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblRLI')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblScriptDefs')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblLanguages')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblTicker')
INSERT [dbo].[tblConfigTables] ([tblName]) VALUES (N'tblWGtext')
GO
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-3dtrackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-borders', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-borders-broadcast', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-borders-html', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-extended-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-fly-over-alerts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-fonts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-help', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-modes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-personalities', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-profiles', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-routes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-scripts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-terminal-maps', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-trackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-triggers', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-configuration-world-guide', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-content', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-content-airports', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-content-logos', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-content-placenames', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'custom-content-splash-screen', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'flight-info-max-parameters', N'15')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'flight-info-parameters', N'eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled,eDistanceToDestination,eTimeToDestination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'flight-info-parameters-display', N'Local Time At Present Position,Local Time At Dest City Name,Estimated Time Of Arrival, Time To Dest City Name,Time Since Departure, Distance To Dest City Name,Latitude,Longitude,Heading, Head wind Tail wind,Wind Direction,Wind Speed,Altitude,Ground Speed,Outside Air Temperature,True Airspeed,Mach,Distance Traveled,Distance To Destination,Time to Destination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'layers', N'distance to poi,trackline,compass,hud,night,borders,north indicator,fodors,pn cities,pn capitals,pn land features,pn water features,pn_airports,terrain,pn airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'layers-display', N'Distance To Poi,Trackline,Compass,HUD,Night,Borders,North Indicator,Fodors,Cities,Capitals,Land Features,Water Features,Airports,Terrain,Airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'makkah-calculation-types', N'mwl,jafari,karachi,isna,makkah,egypt,tehran')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'makkah-calculation-types-display', N'MWL (Muslim World League),Jafari (Shia Ithana Ashari, Leva Research Institute),Karachi (University of Islamic Science),ISNA (Islamic Society of North America),Makkah (Umm Al-Quara University),
Egypt (Egyptian General Authority of Survey),Tehran (Institute of Geophysics, University of Tehran)')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'name', N'baseline feature set')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'script', N'flight-data,image,makkah,item-type4,item-type5')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'script-display', N'Flight Data,Image,Makkah,Item Type 4,Item Type 5')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'ticker-max-speed', N'7')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'ticker-min-speed', N'1')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'ticker-parameters', N'eLocalTimeAtDestination,eLocalTimeAtDeparture,eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestination,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestination,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'ticker-parameters-display', N'Local Time At Destination,Local Time At Departure,Local Time At Departure ,Local Time At Destination,Estimated Time Of Arrival,Time To Destination,Time To Destination,Time Since Departure,Distance To Destination,Distance To Destination,Latitude,Longitude,Heading,Headwind Tailwind,Wind Direction,Wind Speed,Altitude,GroundSpeed,Outside Air Temperature,TrueAirspeed,Mach,DistancTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'views', N'autoplay,flight preview,total route,landscape,overhead,compass,world clocks,time zone, panorama,flight info,command center,makkah,rotating poi')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'views-display', N'Autoplay,Flight Preview,Total Route,Mid Flight,Overhead, Compass,World Clocks,Timezone Globe,Window Seat,Flight Information, Command Center,Makkah,Points of Interest')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'views-max-presets', N'3')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'world-clocks-max-cities', N'12')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (1, N'collins-admin-items', N'flight-data,system-config,briefings,timezone-database,world-guide,insets,download-test-configuration,populations,placenames,airports,world-guide-cities')
GO
--
-- global configuration feature set flags
--
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [value]) VALUES (2, N'collins-admin-items', N'populations,placenames,airports,world-guide-cities')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-3dtrackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-borders', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-borders-broadcast', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-borders-html', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-extended-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-fly-over-alerts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-fonts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-help', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-modes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-personalities', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-profiles', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-routes', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-scripts', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-tab-navigation', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-terminal-maps', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-trackline', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-triggers', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-configuration-world-guide', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-airports', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-logos', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-placenames', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'custom-content-splash-screen', N'true')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'flight-info-max-parameters', N'15')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'flight-info-parameters', N'eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled,eDistanceToDestination,eTimeToDestination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'flight-info-parameters-display', N'Local Time At Present Position,Local Time At Dest City Name,Estimated Time Of Arrival, Time To Dest City Name,Time Since Departure, Distance To Dest City Name,Latitude,Longitude,Heading, Head wind Tail wind,Wind Direction,Wind Speed,Altitude,Ground Speed,Outside Air Temperature,True Airspeed,Mach,Distance Traveled,Distance To Destination,Time to Destination')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'layers', N'distance to poi,trackline,compass,hud,night,borders,north indicator,fodors,pn cities,pn capitals,pn land features,pn water features,pn_airports,terrain,pn airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'layers-display', N'Distance To Poi,Trackline,Compass,HUD,Night,Borders,North Indicator,Fodors,Cities,Capitals,Land Features,Water Features,Airports,Terrain,Airports')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'makkah-calculation-types', N'mwl,jafari,karachi,isna,makkah,egypt,tehran')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'makkah-calculation-types-display', N'MWL (Muslim World League),Jafari (Shia Ithana Ashari, Leva Research Institute),Karachi (University of Islamic Science),ISNA (Islamic Society of North America),Makkah (Umm Al-Quara University),
Egypt (Egyptian General Authority of Survey),Tehran (Institute of Geophysics, University of Tehran)')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'name', N'global configuration feature set')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'script', N'e3DPreFlight,e3DMidFlight,e3DZspace,e3DRli,e3DPanorama,e3DImage,e3DOverhead,e3DVideo,e3DFlightData,e3DRotatingPOI,e3DTotalRoute,e3DTimezone,e3DWorldClocks,e3DRliMecca,e3DHighestRes,e3DMakkah,e3DMiqat,eTickerImage,eTickerFd')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'script-display', N'Flight Preview,Midflight,Global Zoom,Compass,Window Seat,Image,Overhead,Video,Flight Info,Points of Interest,Total Route,Timezone Globe,World Clocks,Makkah Compass,High Resolution,Makkah,Miqat,Ticker Image,Ticker Info')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-max-speed', N'7')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-min-speed', N'1')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-parameters', N'eLocalTimeAtDestination,eLocalTimeAtDeparture,eLocalTimeAtPresentPosition,eLocalTimeAtDestCityName,eEstimatedTimeOfArrival,eTimeToDestination,eTimeToDestCityName,eTimeSinceDeparture,eDistanceToDestination,eDistanceToDestCityName,eLatitude,eLongitude,eHeading,eHeadwindTailwind,eWindDirection,eWindSpeed,eAltitude,eGroundSpeed,eOutsideAirTemperature,eTrueAirspeed,eMach,eDistanceTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'ticker-parameters-display', N'Local Time At Destination,Local Time At Departure,Local Time At Departure ,Local Time At Destination,Estimated Time Of Arrival,Time To Destination,Time To Destination,Time Since Departure,Distance To Destination,Distance To Destination,Latitude,Longitude,Heading,Headwind Tailwind,Wind Direction,Wind Speed,Altitude,GroundSpeed,Outside Air Temperature,TrueAirspeed,Mach,DistancTraveled')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'views', N'autoplay,flight preview,total route,landscape,overhead,compass,world clocks,time zone, panorama,flight info,command center,makkah,rotating poi')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'views-display', N'Autoplay,Flight Preview,Total Route,Mid Flight,Overhead, Compass,World Clocks,Timezone Globe,Window Seat,Flight Information, Command Center,Makkah,Points of Interest')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'views-max-presets', N'3')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'world-clocks-max-cities', N'12')
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'collins-admin-items', N'populations,placenames,airports,world-guide-cities');
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (1, N'editable', N'true');
INSERT [dbo].[tblFeatureSet] ([FeatureSetID], [Name], [Value]) VALUES (2, N'editable', N'true');
GO


INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'e508020a-3e3e-4133-9117-0eaeb38fbdcf', N'Service Access', NULL, N'Service')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'ed3e8547-8ea2-4a77-84cd-2572469a9304', N'Manage Accounts', N'Account management', N'None')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'366ddfbc-4f79-4f50-9573-28d6a5d2d5ad', N'Manage Global Configuration', NULL, N'None')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'e6ac6f6c-d312-4847-a90e-2bbc90b11150', N'Manage Site Settings', N'Full access to site settings and administration', N'None')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'ddd38619-8ac6-45bf-bcb9-353c5ad50e68', N'Reports', N'Report access', N'None')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'dc0d5974-1e1b-4edf-b4ab-3c82f8d3b143', N'View Operator', N'View all operators or a single operator', N'Operator')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'c9f1dd7a-c408-47f3-9df1-4395b4c903b6', N'Manage Aircraft', N'Manage all aircraft or a single aircraft', N'Aircraft')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'faa987cf-2d80-429d-949d-46541275ffe0', N'ManageAircraftByProduct', N'Manage aircraft with a particular product ', N'Product Type')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'd358b15d-8329-4af2-b619-5f3e0bbea264', N'AdministerAircraftByProduct', NULL, N'Product Type')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'cf5ffcb6-6083-47ec-af2b-612a38f81b48', N'ManagePlatformConfiguration', NULL, N'None')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'2f0ab8ba-c889-4109-a385-661a74d3e630', N'ManageProductConfiguration', NULL, N'Product Type')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'dbf91b18-80f8-4356-8d91-8b106b9db443', N'Administer Operator', NULL, N'Operator')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'65faa542-665b-41ff-8cda-b2fa05b41176', N'Manage Operator', N'Manage all operators or a specific operator', N'Operator')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'878af405-47ad-4cc6-8930-bb4bcc5ea11a', N'Manage Role Assignment', N'Role assignment', N'User Role')
INSERT [dbo].[UserClaims] ([ID], [Name], [Description], [ScopeType]) VALUES (N'7c08ec0e-1916-4c61-b386-fb817ff4a8ae', N'Administer Aircraft', NULL, N'Aircraft')
GO

INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'd6ea39a2-6352-4783-857a-1aff668b93fd', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'cf5ffcb6-6083-47ec-af2b-612a38f81b48', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'715ba2da-f312-4956-a144-1c143d2352a1', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'65faa542-665b-41ff-8cda-b2fa05b41176', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'cd8141de-40ff-40aa-9856-1e20158d057c', N'b602b6ee-71e6-40d1-84e6-9730f741a624', N'2f0ab8ba-c889-4109-a385-661a74d3e630', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'97f1d2e4-0bb4-4b8b-ab66-267968cfe37e', N'b602b6ee-71e6-40d1-84e6-9730f741a624', N'65faa542-665b-41ff-8cda-b2fa05b41176', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'8f63ce6d-51e8-406a-ac6d-2a63467e9531', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'ed3e8547-8ea2-4a77-84cd-2572469a9304', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'f25edcd2-3d59-4c80-bfc8-344c754fad94', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'2f0ab8ba-c889-4109-a385-661a74d3e630', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'832983fc-041d-46e1-a8bb-36c001c95715', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'cf5ffcb6-6083-47ec-af2b-612a38f81b48', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'bcb96b8c-37a3-4a16-937c-3d92115b7c88', N'385c8c78-cc0a-4089-932f-2ef0319a36de', N'878af405-47ad-4cc6-8930-bb4bcc5ea11a', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'13152f52-074f-4d48-8383-4c65e2b64f2a', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'65faa542-665b-41ff-8cda-b2fa05b41176', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'39cf1229-997f-4f16-bd82-52bf3224d629', N'385c8c78-cc0a-4089-932f-2ef0319a36de', N'ed3e8547-8ea2-4a77-84cd-2572469a9304', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'97951feb-fd04-4d25-8198-5b72beb75bf3', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'e6ac6f6c-d312-4847-a90e-2bbc90b11150', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'58a8eb69-d236-4476-9e87-5ec840465826', N'b602b6ee-71e6-40d1-84e6-9730f741a624', N'366ddfbc-4f79-4f50-9573-28d6a5d2d5ad', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'33a9bc8d-dd86-419e-92b1-89d1555f3554', N'b602b6ee-71e6-40d1-84e6-9730f741a624', N'ed3e8547-8ea2-4a77-84cd-2572469a9304', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'897813cf-c7bb-4dee-875c-a736e01520ce', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'2f0ab8ba-c889-4109-a385-661a74d3e630', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'c5e2f36f-4f70-40d5-93a5-aeef66b6a465', N'385c8c78-cc0a-4089-932f-2ef0319a36de', N'e6ac6f6c-d312-4847-a90e-2bbc90b11150', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'74bd2f81-8baf-40fa-95a3-b980f80b7997', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'366ddfbc-4f79-4f50-9573-28d6a5d2d5ad', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'55681aa1-d23d-42aa-84e1-d09322448b60', N'b602b6ee-71e6-40d1-84e6-9730f741a624', N'cf5ffcb6-6083-47ec-af2b-612a38f81b48', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
INSERT [dbo].[UserRoleClaims] ([ID], [RoleID], [ClaimID], [AircraftID], [UserRoleID], [ConfigurationID], [ConfigurationDefinitionID], [OperatorID], [ServiceID], [ProductTypeID]) VALUES (N'3e83ad17-7ed3-4a91-924c-e679ee8adb91', N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'366ddfbc-4f79-4f50-9573-28d6a5d2d5ad', NULL, NULL, NULL, NULL, NULL, NULL, NULL)
GO
INSERT [dbo].[UserRoles] ([ID], [Name], [Description], [Hidden], [ThirdParty]) VALUES (N'385c8c78-cc0a-4089-932f-2ef0319a36de', N'Site Administrator', N'Site Administrator', 0, 0)
INSERT [dbo].[UserRoles] ([ID], [Name], [Description], [Hidden], [ThirdParty]) VALUES (N'b602b6ee-71e6-40d1-84e6-9730f741a624', N'SWOPs Administrator', N'SWOPs Administrator', 0, 0)
INSERT [dbo].[UserRoles] ([ID], [Name], [Description], [Hidden], [ThirdParty]) VALUES (N'03a2057b-e3d3-4bf4-a344-daf7259b972b', N'Engineering Administrator', N'Engineering Administrator', 0, 0)
GO

GO
IF NOT EXISTS (SELECT ImageType FROM tblImageType WHERE ImageType='Logo')
INSERT INTO tblImageType VALUES('Logo','Image Type for Logo')

IF NOT EXISTS (SELECT ImageType FROM tblImageType WHERE ImageType='Splash')
INSERT INTO tblImageType VALUES('Splash','Image Type for Splash')

IF NOT EXISTS (SELECT ImageType FROM tblImageType WHERE ImageType='Script')
INSERT INTO tblImageType VALUES('Script','Image Type for Script')

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='1280x800')
INSERT INTO tblImageres SELECT '1280x800',1,'MOBILE DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='1334x750')
INSERT INTO tblImageres SELECT '1334x750',0,'TAB DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='1920x1080')
INSERT INTO tblImageres SELECT '1920x1080',0,'MOBILE DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='2048x1536')
INSERT INTO tblImageres SELECT '2048x1536',0,'TAB DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='2224x1668')
INSERT INTO tblImageres SELECT '2224x1668',0,'MOBILE DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='2280x1080')
INSERT INTO tblImageres SELECT '2280x1080',0,'TAB DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='2388x1668')
INSERT INTO tblImageres SELECT '2388x1668',0,'MOBILE DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='2560x1600')
INSERT INTO tblImageres SELECT '2560x1600',0,'TAB DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='2732x2048')
INSERT INTO tblImageres SELECT '2732x2048',0,'MOBILE DISPLAY'

IF NOT EXISTS (SELECT resolution FROM tblImageres WHERE resolution='3200x1440')
INSERT INTO tblImageres SELECT '3200x1440',0,'TAB DISPLAY'

UPDATE tblImageres SET IsDefault=1 WHERE ID=3
UPDATE tblImageres SET IsDefault=0 WHERE ID=1;
UPDATE tblImageres SET Description='Various Android devices' WHERE ID IN(10,8,6,1)
UPDATE tblImageres SET Description='Full HD, Various Android Devices, Collins DEU' WHERE ID IN(3)
UPDATE tblImageres SET Description='iPad Pro 12"' WHERE ID IN(9)
UPDATE tblImageres SET Description='iPad Pro 11"' WHERE ID IN(7)
UPDATE tblImageres SET Description='iPad Air 3/Pro 10.5"' WHERE ID IN(5)
UPDATE tblImageres SET Description='iPad Mini//4/5/6/Air' WHERE ID IN(4)
UPDATE tblImageres SET Description='iPhone SE 2nd gen' WHERE ID IN(2)
GO
