CREATE TABLE [dbo].[tblSpellingPoiPanel]
(
	[SpellingID] int NOT NULL IDENTITY (1, 1),
	[GeoRefId] int NULL,
	[Description] nvarchar(255) NULL,
	[TimeStampModified] timestamp NOT NULL,
	[SourceDate] datetime NULL,
	[lang_ar] nvarchar(255) NULL,
	[lang_az] nvarchar(255) NULL,
	[lang_bn] nvarchar(255) NULL,
	[lang_bo] nvarchar(255) NULL,
	[lang_da] nvarchar(255) NULL,
	[lang_de] nvarchar(255) NULL,
	[lang_di] nvarchar(255) NULL,
	[lang_el] nvarchar(255) NULL,
	[lang_en] nvarchar(255) NULL,
	[lang_ep] nvarchar(255) NULL,
	[lang_es] nvarchar(255) NULL,
	[lang_fi] nvarchar(255) NULL,
	[lang_fr] nvarchar(255) NULL,
	[lang_he] nvarchar(255) NULL,
	[lang_hi] nvarchar(255) NULL,
	[lang_hk] nvarchar(255) NULL,
	[lang_hu] nvarchar(255) NULL,
	[lang_id] nvarchar(255) NULL,
	[lang_is] nvarchar(255) NULL,
	[lang_it] nvarchar(255) NULL,
	[lang_ja] nvarchar(255) NULL,
	[lang_kk] nvarchar(255) NULL,
	[lang_ko] nvarchar(255) NULL,
	[lang_mn] nvarchar(255) NULL,
	[lang_ms] nvarchar(255) NULL,
	[lang_nl] nvarchar(255) NULL,
	[lang_pl] nvarchar(255) NULL,
	[lang_pt] nvarchar(255) NULL,
	[lang_ro] nvarchar(255) NULL,
	[lang_ru] nvarchar(255) NULL,
	[lang_sm] nvarchar(255) NULL,
	[lang_sp] nvarchar(255) NULL,
	[lang_sr] nvarchar(255) NULL,
	[lang_sv] nvarchar(255) NULL,
	[lang_th] nvarchar(255) NULL,
	[lang_tk] nvarchar(255) NULL,
	[lang_to] nvarchar(255) NULL,
	[lang_tr] nvarchar(255) NULL,
	[lang_uz] nvarchar(255) NULL,
	[lang_vi] nvarchar(255) NULL,
	[lang_lk] nvarchar(255) NULL,
	[lang_zh] nvarchar(255) NULL
)
GO
ALTER TABLE [dbo].[tblSpellingPoiPanel] 
 ADD CONSTRAINT [PK_tblSpellingPoiPanel]
	PRIMARY KEY CLUSTERED ([SpellingID] ASC)