
IF (OBJECT_ID('cust.FK_tblWorldClockCityMap_WorldClockCities', 'F') IS NOT NULL)
BEGIN
    ALTER TABLE cust.tblWorldClockCitiesMap
    DROP CONSTRAINT FK_tblWorldClockCityMap_WorldClockCities
END

IF (OBJECT_ID('cust.tblWorldClockCities', 'U') IS NOT NULL)
BEGIN

DECLARE @tmpTable Table(WorldClockCityID INT, WorldClockCities XML)

INSERT INTO @tmpTable  SELECT * FROM cust.tblWorldClockCities

DROP TABLE cust.tblWorldClockCities

CREATE TABLE [cust].[tblWorldClockCities] (
    [WorldClockCityID] INT IDENTITY(1,1) NOT NULL,
    [WorldClockCities] XML NULL,
    CONSTRAINT [PK_WorldClockCities] PRIMARY KEY CLUSTERED ([WorldClockCityID] ASC)
);

SET IDENTITY_INSERT [cust].[tblWorldClockCities] ON

INSERT INTO cust.tblWorldClockCities(WorldClockCityID,WorldClockCities)  SELECT * FROM @tmpTable

SET IDENTITY_INSERT [cust].[tblWorldClockCities] OFF

ALTER TABLE [cust].[tblWorldClockCitiesMap]
    ADD CONSTRAINT [FK_tblWorldClockCityMap_WorldClockCities] FOREIGN KEY ([WorldClockCityID]) REFERENCES [cust].[tblWorldClockCities] ([WorldClockCityID]) ON DELETE CASCADE;
END


IF COL_LENGTH('dbo.tblTasks','Cancelled') IS NULL
BEGIN
    ALTER TABLE [dbo].[tblTasks] ADD Cancelled BIT DEFAULT 0;
    EXEC SP_EXECUTESQL N'UPDATE [dbo].[tblTasks] SET [dbo].[tblTasks].[Cancelled] = 0'
END 

IF COL_LENGTH('dbo.tblTaskType','ShouldShowInBuildDashboard') IS NULL
BEGIN
    ALTER TABLE [dbo].[tblTaskType] ADD ShouldShowInBuildDashboard BIT DEFAULT 0;
    EXEC SP_EXECUTESQL N'UPDATE tblTaskType SET ShouldShowInBuildDashboard = 0'
END 
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'Action'
          AND Object_ID = Object_ID(N'dbo.tblImageMap'))
BEGIN
ALTER TABLE tblImageMap ADD Action NVARCHAR(50)
END

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'CustomChangeBitMask'
          AND Object_ID = Object_ID(N'dbo.tblCountry'))
BEGIN
ALTER TABLE dbo.tblCountry ADD CustomChangeBitMask INT
END
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'CustomChangeBitMask'
          AND Object_ID = Object_ID(N'dbo.tblRegionSpelling'))
BEGIN
ALTER TABLE dbo.tblRegionSpelling ADD CustomChangeBitMask INT
END
IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'CustomChangeBitMask'
          AND Object_ID = Object_ID(N'dbo.tblCountrySpelling '))
BEGIN
ALTER TABLE dbo.tblCountrySpelling  ADD CustomChangeBitMask INT
END
IF NOT EXISTS(SELECT 1 FROM sys.columns
WHERE Name = N'CustomChangeBitMask'
AND Object_ID = Object_ID(N'dbo.tblAirportInfo '))
BEGIN
ALTER TABLE dbo.tblAirportInfo ADD CustomChangeBitMask INT
END

IF NOT EXISTS(SELECT 1 FROM sys.columns
         WHERE Name = N'LastUpdateDateTime'
         AND Object_ID = Object_ID(N'dbo.tblConfigurations'))
BEGIN
ALTER TABLE tblConfigurations ADD LastUpdateDateTime DATETIME DEFAULT GETDATE();
EXEC SP_EXECUTESQL N'UPDATE tblConfigurations SET LastUpdateDateTime=GETDATE();'
END

IF NOT EXISTS(SELECT 1 FROM sys.columns
         WHERE Name = N'IsUHF'
         AND Object_ID = Object_ID(N'dbo.tblASXiInset'))
BEGIN
	ALTER TABLE tblASXiInset ADD IsUHF BIT;
END

IF NOT EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'TopLevelPartNumber'
          AND Object_ID = Object_ID(N'dbo.tblProducts'))
BEGIN
ALTER TABLE dbo.tblProducts ADD TopLevelPartNumber VARCHAR(255)
END
GO



/* ---------------------------------------------------- */
/*  Generated by Lakshmikanth 		*/
/*  Created On : 01-Aug-2022 5:30:09 PM 				*/
/*  Description   : Added Identity Columns for tblCountry, tblFonts, tblFontFamily , tblFontCategory ,tblFontMarker 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF (OBJECT_ID('dbo.FK_tblCountryMap_tblCountry', 'F') IS NOT NULL)
BEGIN
    ALTER TABLE dbo.[tblCountryMap] DROP CONSTRAINT FK_tblCountryMap_tblCountry
END
GO

IF (OBJECT_ID('dbo.FK_tblCountrySpelling_tblCountry', 'F') IS NOT NULL)
BEGIN
    ALTER TABLE dbo.[tblCountrySpelling] DROP CONSTRAINT FK_tblCountrySpelling_tblCountry
END
GO



IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblCountry]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblCountry]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblCountry]
(
	[ID] int NOT NULL IDENTITY (1, 1),
	[Description] nvarchar(50) NULL,
	[CountryCode] nvarchar(2) NULL,
	[ISO3166Code] nvarchar(2) NULL,
	[RegionID] int NULL,
	[CountryID] int NULL,
	[CustomChangeBitMask] int
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[tblCountry] 
 ADD CONSTRAINT [PK_tblCountry]
	PRIMARY KEY CLUSTERED ([ID] ASC)
GO



/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblCountryMap_tblConfigurations]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblCountryMap] DROP CONSTRAINT [FK_tblCountryMap_tblConfigurations]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblCountryMap_tblCountry]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblCountryMap] DROP CONSTRAINT [FK_tblCountryMap_tblCountry]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblCountryMap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblCountryMap]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblCountryMap]
(
	[ConfigurationID] int NULL,
	[CountryID] int NULL,
	[PreviousCountryID] int NULL,
	[IsDeleted] bit NULL DEFAULT 0,
	[TimeStampModified] timestamp NULL,
	[LastModifiedBy] nvarchar(50) NULL,
	[Action] nvarchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE NONCLUSTERED INDEX [IXFK_tblCountryMap_tblConfigurations] 
 ON [dbo].[tblCountryMap] ([ConfigurationID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_tblCountryMap_tblCountry] 
 ON [dbo].[tblCountryMap] ([CountryID] ASC)
GO

/* Create Foreign Key Constraints */

IF (OBJECT_ID('dbo.FK_tblCountryMap_tblConfigurations', 'F') IS NULL)
BEGIN
 ALTER TABLE [dbo].[tblCountryMap] ADD CONSTRAINT [FK_tblCountryMap_tblConfigurations]
	FOREIGN KEY ([ConfigurationID]) REFERENCES [dbo].[tblConfigurations] ([ConfigurationID]) ON DELETE Cascade ON UPDATE No Action
END
GO


IF (OBJECT_ID('dbo.FK_tblCountryMap_tblCountry', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblCountryMap] ADD CONSTRAINT [FK_tblCountryMap_tblCountry]
	FOREIGN KEY ([CountryID]) REFERENCES [dbo].[tblCountry] ([ID]) ON DELETE Cascade ON UPDATE No Action
END

GO

/* Drop Tables */

IF (OBJECT_ID('dbo.FK_tblFontMap_tblFont', 'F') IS NOT NULL)
BEGIN
ALTER TABLE dbo.[tblFontMap] DROP CONSTRAINT FK_tblFontMap_tblFont
END
GO


IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFont]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFont]


/* Create Tables */

CREATE TABLE [dbo].[tblFont]
(
	[ID] int NOT NULL IDENTITY (1, 1),
	[FontID] int NOT NULL,
	[Description] nvarchar(255) NULL,
	[Size] INT NULL,
	[Color] nvarchar(8) NULL,
	[ShadowColor] nvarchar(8) NULL,
	[FontFaceId] INT NULL,
	[FontStyle] INT NULL

)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[tblFont] 
 ADD CONSTRAINT [PK_tblFont]
	PRIMARY KEY CLUSTERED ([ID] ASC)
GO


/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontMap_tblConfigurations]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontMap] DROP CONSTRAINT [FK_tblFontMap_tblConfigurations]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontMap_tblFont]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontMap] DROP CONSTRAINT [FK_tblFontMap_tblFont]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontMap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontMap]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontMap]
(
	[ConfigurationID] int NULL,
	[FontID] int NULL,
	[PreviousFontID] int NULL,
	[IsDeleted] bit NULL DEFAULT 0,
	[TimeStampModified] timestamp NOT NULL,
	[LastModifiedBy] nvarchar(50) NULL,
	[Action] nvarchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE NONCLUSTERED INDEX [IXFK_tblFontMap_tblConfigurations] 
 ON [dbo].[tblFontMap] ([ConfigurationID] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_tblFontMap_tblFont] 
 ON [dbo].[tblFontMap] ([FontID] ASC)
GO

/* Create Foreign Key Constraints */

IF (OBJECT_ID('dbo.FK_tblFontMap_tblConfigurations', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontMap] ADD CONSTRAINT [FK_tblFontMap_tblConfigurations]
	FOREIGN KEY ([ConfigurationID]) REFERENCES [dbo].[tblConfigurations] ([ConfigurationID]) ON DELETE Cascade ON UPDATE No Action
END
GO


IF (OBJECT_ID('dbo.FK_tblFontMap_tblFont', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontMap] ADD CONSTRAINT [FK_tblFontMap_tblFont]
	FOREIGN KEY ([FontID]) REFERENCES [dbo].[tblFont] ([ID]) ON DELETE Cascade ON UPDATE No Action
END
GO

IF (OBJECT_ID('dbo.FK_tblFontCategoryMap_tblFontCategory', 'F') IS NOT NULL)
BEGIN
ALTER TABLE dbo.[tblFontCategoryMap] DROP CONSTRAINT FK_tblFontCategoryMap_tblFontCategory
END
GO


IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontCategory]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontCategory]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontCategory]
(
	[FontCategoryID] int NOT NULL IDENTITY (1, 1),
	[GeoRefIdCatTypeID] int NULL DEFAULT 0,
	[LanguageID] int NULL DEFAULT 0,
	[FontID] int NULL,
	[MarkerID] int NULL,
	[IMarkerID] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[tblFontCategory] 
 ADD CONSTRAINT [PK_tblFontCategory]
	PRIMARY KEY CLUSTERED ([FontCategoryID] ASC)
GO



/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontCategoryMap_tblConfigurations]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontCategoryMap] DROP CONSTRAINT [FK_tblFontCategoryMap_tblConfigurations]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontCategoryMap_tblFontCategory]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontCategoryMap] DROP CONSTRAINT [FK_tblFontCategoryMap_tblFontCategory]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontCategoryMap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontCategoryMap]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontCategoryMap]
(
	[ConfigurationID] int NULL,
	[FontCategoryID] int NULL,
	[PreviousFontCategoryID] int NULL,
	[IsDeleted] bit NULL DEFAULT 0,
	[TimeStampModified] timestamp NOT NULL,
	[LastModifiedBy] nvarchar(50) NULL,
	[Action] nvarchar(50) NULL
)
GO

/* Create Foreign Key Constraints */

IF (OBJECT_ID('dbo.FK_tblFontCategoryMap_tblConfigurations', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontCategoryMap] ADD CONSTRAINT [FK_tblFontCategoryMap_tblConfigurations]
	FOREIGN KEY ([ConfigurationID]) REFERENCES [dbo].[tblConfigurations] ([ConfigurationID]) ON DELETE Cascade ON UPDATE No Action
END
GO


IF (OBJECT_ID('dbo.FK_tblFontCategoryMap_tblFontCategory', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontCategoryMap] ADD CONSTRAINT [FK_tblFontCategoryMap_tblFontCategory]
	FOREIGN KEY ([FontCategoryID]) REFERENCES [dbo].[tblFontCategory] ([FontCategoryID]) ON DELETE Cascade ON UPDATE No Action
END
GO

/* Drop Tables */
IF (OBJECT_ID('dbo.FK_tblFontFamilyMap_tblFontFamily', 'F') IS NOT NULL)
BEGIN
ALTER TABLE dbo.[tblFontFamilyMap] DROP CONSTRAINT FK_tblFontFamilyMap_tblFontFamily
END
GO


IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontFamily]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontFamily]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontFamily]
(
	[FontFamilyID] int NOT NULL IDENTITY (1, 1),
	[FontFaceID] int NULL,
	[FaceName] nvarchar(255) NULL,
	[FileName] nvarchar(255) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[tblFontFamily] 
 ADD CONSTRAINT [PK_tblFontFamily]
	PRIMARY KEY CLUSTERED ([FontFamilyID] ASC)
GO


/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontFamilyMap_tblConfigurations]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontFamilyMap] DROP CONSTRAINT [FK_tblFontFamilyMap_tblConfigurations]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontFamilyMap_tblFontFamily]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontFamilyMap] DROP CONSTRAINT [FK_tblFontFamilyMap_tblFontFamily]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontFamilyMap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontFamilyMap]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontFamilyMap]
(
	[ConfigurationID] int NULL,
	[FontFamilyID] int NULL,
	[PreviousFontFamilyID] int NULL,
	[IsDeleted] bit NULL DEFAULT 0,
	[TimeStampModified] timestamp NOT NULL,
	[LastModifiedBy] nvarchar(50) NULL,
	[Action] nvarchar(50) NULL
)
GO

/* Create Foreign Key Constraints */

IF (OBJECT_ID('dbo.FK_tblFontFamilyMap_tblConfigurations', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontFamilyMap] ADD CONSTRAINT [FK_tblFontFamilyMap_tblConfigurations]
	FOREIGN KEY ([ConfigurationID]) REFERENCES [dbo].[tblConfigurations] ([ConfigurationID]) ON DELETE Cascade ON UPDATE No Action
END
GO


IF (OBJECT_ID('dbo.FK_tblFontFamilyMap_tblFontFamily', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontFamilyMap] ADD CONSTRAINT [FK_tblFontFamilyMap_tblFontFamily]
	FOREIGN KEY ([FontFamilyID]) REFERENCES [dbo].[tblFontFamily] ([FontFamilyID]) ON DELETE Cascade ON UPDATE No Action
END
GO


/* Drop Tables */


IF (OBJECT_ID('dbo.FK_tblFontMarkerMap_tblFontMarker', 'F') IS NOT NULL)
BEGIN
ALTER TABLE dbo.[tblFontMarkerMap] DROP CONSTRAINT FK_tblFontMarkerMap_tblFontMarker
END
GO



IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontMarker]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontMarker]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontMarker]
(
	[FontMarkerID] int NOT NULL IDENTITY (1, 1),
	[MarkerID] int NOT NULL DEFAULT 0,
	[Filename] nvarchar(255) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[tblFontMarker] 
 ADD CONSTRAINT [PK_tblFontMarker]
	PRIMARY KEY CLUSTERED ([FontMarkerID] ASC)
GO



/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontMarkerMap_tblConfigurations]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontMarkerMap] DROP CONSTRAINT [FK_tblFontMarkerMap_tblConfigurations]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[FK_tblFontMarkerMap_tblFontMarker]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dbo].[tblFontMarkerMap] DROP CONSTRAINT [FK_tblFontMarkerMap_tblFontMarker]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblFontMarkerMap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dbo].[tblFontMarkerMap]
GO

/* Create Tables */

CREATE TABLE [dbo].[tblFontMarkerMap]
(
	[ConfigurationID] int NOT NULL,
	[FontMarkerID] int NULL,
	[PreviousFontMarkerID] int NULL DEFAULT -1,
	[isDeleted] bit NULL DEFAULT 0,
	[TimeStampModified] timestamp NULL,
	[LastModifiedBy] nvarchar(50) NULL,
	[Action] nvarchar(50) NULL
)
GO

/* Create Foreign Key Constraints */

IF (OBJECT_ID('dbo.FK_tblFontMarkerMap_tblConfigurations', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontMarkerMap] ADD CONSTRAINT [FK_tblFontMarkerMap_tblConfigurations]
	FOREIGN KEY ([ConfigurationID]) REFERENCES [dbo].[tblConfigurations] ([ConfigurationID]) ON DELETE Cascade ON UPDATE No Action
END
GO

IF (OBJECT_ID('dbo.FK_tblFontMarkerMap_tblFontMarker', 'F') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblFontMarkerMap] ADD CONSTRAINT [FK_tblFontMarkerMap_tblFontMarker]
	FOREIGN KEY ([FontMarkerID]) REFERENCES [dbo].[tblFontMarker] ([FontMarkerID]) ON DELETE Cascade ON UPDATE No Action
END
GO


------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblPartNumberCollection]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[tblPartNumberCollection]
(
    [PartNumberCollectionID] int NOT NULL,
    [Name] varchar(255),
    [Description] varchar(512)
)  
END


/* Create Primary Keys, Indexes, Uniques, Checks */
IF (OBJECT_ID('PK_tblPartNumberCollection') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblPartNumberCollection] 
	ADD CONSTRAINT [PK_tblPartNumberCollection]
	PRIMARY KEY CLUSTERED ([PartNumberCollectionID] ASC)
END
GO

/* Create Tables */

IF NOT EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblPartNumber]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[tblPartNumber]
(
    [PartNumberID] int NOT NULL,
	[PartNumberCollectionID] int,
    [Name]varchar(255),
    [Description] varchar(512),
    [DefaultPartNumber] varchar(255),
	[Order] int
)
END


/* Create Primary Keys, Indexes, Uniques, Checks */
IF (OBJECT_ID('PK_tblPartNumber') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblPartNumber] 
	 ADD CONSTRAINT [PK_tblPartNumber]
     PRIMARY KEY CLUSTERED ([PartNumberID] ASC)
END
GO

/*creating foreign key constraint */
IF (OBJECT_ID('FK_tblPartNumber_tblPartNumberCollection') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblPartNumber] ADD CONSTRAINT [FK_tblPartNumber_tblPartNumberCollection]
	FOREIGN KEY ([PartNumberCollectionID]) REFERENCES [dbo].[tblPartNumberCollection] ([PartNumberCollectionID]) ON DELETE Cascade ON UPDATE No Action
END
GO


/* Create Tables */

IF NOT  EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblConfigurationDefinitionPartNumber]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[tblConfigurationDefinitionPartNumber]
(
    [ConfigurationDefinitionID] int NOT NULL ,
	[PartNumberID] int NOT NULL,
	[Value] varchar(255)
)
END 


/* Create Primary Keys, Indexes, Uniques, Checks */
IF (OBJECT_ID('PK_tblConfigurationDefinitionPartNumber') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblConfigurationDefinitionPartNumber] 
	ADD CONSTRAINT [PK_tblConfigurationDefinitionPartNumber]
    PRIMARY KEY CLUSTERED ([ConfigurationDefinitionID],[PartNumberID] ASC)
END
GO


/*creating foreign key constraint */
IF (OBJECT_ID('FK_tblConfigurationDefinitionPartNumber_tblConfigurationDefinitions') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblConfigurationDefinitionPartNumber] ADD CONSTRAINT [FK_tblConfigurationDefinitionPartNumber_tblConfigurationDefinitions]
	FOREIGN KEY ([ConfigurationDefinitionID]) REFERENCES [dbo].[tblConfigurationDefinitions] ([ConfigurationDefinitionID]) ON DELETE Cascade ON UPDATE No Action
END
GO

IF (OBJECT_ID('FK_tblConfigurationDefinitionPartNumber_tblPartNumber') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblConfigurationDefinitionPartNumber] ADD CONSTRAINT [FK_tblConfigurationDefinitionPartNumber_tblPartNumber]
	FOREIGN KEY ([PartNumberID]) REFERENCES [dbo].[tblPartNumber] ([PartNumberID]) ON DELETE Cascade ON UPDATE No Action
END
GO

/* Add column */

IF NOT EXISTS(SELECT 1 FROM sys.columns
         WHERE Name = N'PartNumberCollectionID'
         AND Object_ID = Object_ID(N'dbo.tblOutputTypes'))
BEGIN
	ALTER TABLE tblOutputTypes ADD PartNumberCollectionID INT NULL;
END
GO

/*creating foreign key constraint */
IF (OBJECT_ID('FK_tblOutputTypes_tblPartNumberCollection') IS NULL)
BEGIN
ALTER TABLE [dbo].[tblOutputTypes] ADD CONSTRAINT [FK_tblOutputTypes_tblPartNumberCollection]
	FOREIGN KEY ([PartNumberCollectionID]) REFERENCES [dbo].[tblPartNumberCollection] ([PartNumberCollectionID]) ON DELETE Cascade ON UPDATE No Action
END
GO


/* Create Tables */

IF NOT  EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblModList]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[tblModList]
(
    [ModlistID] INT IDENTITY (1,1) NOT NULL ,
	[FileJSON] NVARCHAR(MAX),
	[Row] INT NOT NULL,
	[Col] INT NOT NULL,
	[Resolution]  INT NOT NULL ,
	[isDirty]  BIT NULL DEFAULT 0,
)
    
END 
GO
/* Create Primary Keys, Indexes, Uniques, Checks */
IF(OBJECT_ID('dbo.PK_tblModList','P')IS NULL)
BEGIN
ALTER TABLE [dbo].[tblModList] 
	   ADD CONSTRAINT [PK_tblModList]
       PRIMARY KEY CLUSTERED ([ModlistID] ASC)
END
GO


IF NOT  EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dbo].[tblModListMap]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
BEGIN
CREATE TABLE [dbo].[tblModListMap]
(
	[ID] INT IDENTITY (1,1) NOT NULL,
    [ModlistID] INT NOT NULL ,
	[ConfigurationID] INT NOT NULL,
	[PreviousModlistID] INT NOT NULL,
	[IsDeleted] BIT NULL DEFAULT 0,
	[TimeStampModified] timestamp NULL,
	[LastModifiedBy] NVARCHAR(50) NULL,
	[Action] NVARCHAR(50) NULL
)
END
GO

IF(OBJECT_ID('dbo.PK_tblModListMap','P')IS NULL)
BEGIN
		ALTER TABLE [dbo].[tblModListMap] 
	 ADD CONSTRAINT [PK_tblModListMap]
     PRIMARY KEY CLUSTERED ([ID] ASC)
END
GO

/*creating foreign key constraint */
IF(OBJECT_ID('dbo.FK_tblModListMap_tblModList','F')IS NULL)
BEGIN
		ALTER TABLE [dbo].[tblModListMap] ADD CONSTRAINT [FK_tblModListMap_tblModList]
			FOREIGN KEY ([ModlistID]) REFERENCES [dbo].[tblModList] ([ModlistID]) ON DELETE Cascade ON UPDATE No Action

END
GO



